volumes:
  postgres-data:
  kestra-data:


networks:
  kestra:


services:
  # 1. Database for Kestra
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    networks:
      - kestra
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kestra" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Kestra Server (Standalone)
  kestra:
    user: root
    build: ./kestra
    # image: kestra/kestra:latest
    command: server local
    ports:
      - "8080:8080" # Web UI
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/IAS/Desktop/projects/ApiforgeX:/app/projects/ApiforgeX
      - ./kestra/flows:/app/flows # Auto-load flows
    environment:
      # FIX: Explicit environment variables (Impossible to ignore)
      KESTRA_JDBC_TYPE: postgres
      KESTRA_DATASOURCES_POSTGRES_URL: jdbc:postgresql://postgres:5432/kestra
      KESTRA_DATASOURCES_POSTGRES_DRIVER_CLASS_NAME: org.postgresql.Driver
      KESTRA_DATASOURCES_POSTGRES_USERNAME: kestra
      KESTRA_DATASOURCES_POSTGRES_PASSWORD: kestra
    networks:
      - kestra
    depends_on:
      postgres:
        condition: service_healthy
